### ISSUE TITLE
[버그] MainPage 내에 Layout 배치 깨짐

### ISSUE THREAD

**Issue by KNU-K** [TaskSprints/auction-front#10]
### 설명

MainPage 내에 Component 를 구성했는데 내부적인 Position 옵션이 이상함

### 스크린샷
![image](https://github.com/user-attachments/assets/0d86e289-37fc-4324-a2eb-9d4a26427094)

**Comment by JIHUN-HA** [comment]
#10 문제 해결

**Comment by KNU-K** [comment]
👍  해결 완료
